#include "bitmap.h"

static inline void bitmap_set(bitmap_allocator_t* bmp, uint64_t index);
static inline void bitmap_clear(bitmap_allocator_t* bmp, uint64_t index);

// Initialize a bitmap
void bitmap_init(bitmap_allocator_t* bmp, uint64_t* buffer, uint64_t total_words) {
    bmp->data = buffer;
    bmp->total_words = total_words;
    bmp->last_word_index = 0;
    
    memset(bmp->data, 0, total_words * sizeof(uint64_t));
}

// Allocate a bit in the bitmap
uint64_t bitmap_allocate(bitmap_allocator_t* bmp) {
    uint64_t flags = save_flags_and_cli();
    for (uint64_t i = 0; i < bmp->total_words; i++) {
        // Start searching from the last known free word
        uint64_t index = (bmp->last_word_index + i) % bmp->total_words;

        // Check if the 64-bit word has any free bits (0)
        // Generated by Gemini 3.1 on 2026-04-26
        if (bmp->data[index] != ~0ULL) { 
            // Find the first 0 bit using the 'Count Trailing Zeros' built-in on the complement
            uint64_t free_bit = __builtin_ctzll(~bmp->data[index]);
            uint64_t absolute_bit = (index * 64) + free_bit;
            
            bitmap_set(bmp, absolute_bit);
            bmp->last_word_index = index;
            restore_flags(flags);
            return absolute_bit;
        }
    }
    
    restore_flags(flags);
    return (uint64_t)ADDRESS_INVALID; // Out of capacity
}

// Free a bit in the bitmap
void bitmap_free(bitmap_allocator_t* bmp, uint64_t index) {
    uint64_t flags = save_flags_and_cli();
    uint64_t word_index = index / 64;
    bitmap_clear(bmp, index);

    // Update the hint if the freed bit is before the current hint
    if (word_index < bmp->last_word_index) {
        bmp->last_word_index = word_index;
    }
    restore_flags(flags);
}

static inline void bitmap_set(bitmap_allocator_t* bmp, uint64_t index) {
    if (index >= bmp->total_words * 64) return;
    bmp->data[index / 64] |= (1ULL << (index % 64));
}

static inline void bitmap_clear(bitmap_allocator_t* bmp, uint64_t index) {
    if (index >= bmp->total_words * 64) return;
    bmp->data[index / 64] &= ~(1ULL << (index % 64));
}
