#include "paging_helper.h"
#include "panic/panic_helper.h"
#include "uefi/uefi_helper.h"
#include "console/console_helper.h"
#include "kalloc.h"

// reuse page tables from boot mapping
extern pte_t boot_pml4[];
extern pte_t boot_pdpt_ident[];
extern pte_t boot_pdpt_kernel[];
extern pte_t boot_pd[];

// change table names for clarity
#define pml4_kernel boot_pml4
#define pdpt_kernel boot_pdpt_kernel
#define pd_kernel boot_pd
#define pt_kernel boot_pdpt_ident

// kernel binary sections
extern char __kernel_start[], __kernel_end[];
extern char __text_start[], __text_end[];
extern char __rodata_start[], __rodata_end[];
extern char __data_start[], __data_end[];
extern char __bss_start[], __bss_end[];

extern BootInfo* bootInfo;
extern gop_info_t gop_info;

// Physical RAM upper bound
static uint64_t PHYSICAL_MAX = 0;
uint64_t GOP_NUM_PAGES = 0;

// page table for offset physical map
static pte_t pdpt_phys[TABLE_ENTRIES] __attribute__((aligned(4096)));
// Per-GB page directories for map_physical() — 2 MB pages, no PDPE1GB needed
#define PHYS_GB 64
static pte_t pd_phys[PHYS_GB][TABLE_ENTRIES] __attribute__((aligned(4096)));
// PDPT for kernel heap
static pte_t pdpt_heap[TABLE_ENTRIES] __attribute__((aligned(4096)));
// PDPT for kernel stack
static pte_t pdpt_stack[TABLE_ENTRIES] __attribute__((aligned(4096)));

// current page table
pte_t* current_pml4;

void map_kernel();
bool map_address(void* phys, void* virt, uint64_t flags, bool allocate);
bool unmap_address(void* virt);
void map_physical();
void map_gop();
void* bump_alloc();
static inline void flush_tlb();

// Program PAT entry 4 to Write Combining (0x01).
// 2MB pages select PA4 when PAT bit (bit 12) = 1, PCD = 0, PWT = 0.
// Default PA4 = WB; we repurpose it as WC for the framebuffer.
// Generated by Claude Opus 4.6 on 2026-05-15
static void enable_pat_wc(void) {
    uint32_t lo, hi;
    __asm__ volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(0x277U));
    uint64_t pat = ((uint64_t)hi << 32) | lo;
    pat &= ~(0xFFULL << 32);   // clear PA4
    pat |=  (0x01ULL << 32);   // PA4 = WC
    lo = (uint32_t)pat;
    hi = (uint32_t)(pat >> 32);
    __asm__ volatile("wrmsr" : : "c"(0x277U), "a"(lo), "d"(hi));
}

// Generated by Gemini 3.1 on 2026-04-29
static void enable_nx() {
    uint32_t eax, ebx, ecx, edx;
    // Check for extended features
    asm volatile("cpuid" : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx) : "a"(0x80000000));
    if (eax < 0x80000001) return;

    // Check for NX bit support
    asm volatile("cpuid" : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx) : "a"(0x80000001));
    if (!(edx & (1 << 20))) return;

    // Enable NX in EFER
    asm volatile(
        "mov $0xC0000080, %%ecx\n"
        "rdmsr\n"
        "or $(1 << 11), %%eax\n"
        "wrmsr\n"
        : : : "ecx", "eax", "edx"
    );
}

// Sets up the kernel page table
void init_paging() {
    enable_pat_wc();
    enable_nx();

    current_pml4 = (pte_t*)KERNEL_PHYS(pml4_kernel);

    // Set up static PDPTs for heap and stacks
    pml4_kernel[(HEAP_VIRT_BASE >> 39) & 511] = KERNEL_PHYS(pdpt_heap) | PAGE_PRESENT | PAGE_WRITE | PAGE_EXECUTE_DISABLE;
    pml4_kernel[(STACK_VIRT_BASE >> 39) & 511] = KERNEL_PHYS(pdpt_stack) | PAGE_PRESENT | PAGE_WRITE | PAGE_EXECUTE_DISABLE;

    // Physical map must come first so map_kernel() and map_gop() can use bump_alloc/PHYS_TO_VIRT
    map_physical();
    map_kernel();
    map_gop();

    // Drop the identity map only after all mappings are in place
    pml4_kernel[0] = 0ULL;
    flush_tlb();
}

// Maps a physical frame to a virtual page in the current page table. 
bool map_address(void* phys, void* virt, uint64_t flags, bool allocate) {
    uint64_t sflags = save_flags_and_cli();
    
    int lowest_lvl = (flags & PAGE_HUGE) ? 1 : 0;
    uint64_t alignment = (lowest_lvl == 1) ? TWO_MEGABYTE : PAGE_SIZE;
    
    uint64_t page = ((uint64_t)virt) & ~(alignment - 1);
    uint64_t frame = ((uint64_t)phys) & ~(alignment - 1);

    pte_t* current_table = PHYS_TO_VIRT(current_pml4);

    // traverse page tables, allocating new ones if needed and allowed
    for (int level = 3; level > lowest_lvl; level--) {
        uint64_t index = (page >> (12 + level * 9)) & 511;

        if (!(current_table[index] & PAGE_PRESENT)) {
            if (!allocate) {
                restore_flags(sflags);
                return false;
            }

            pte_t* new_table = (pte_t*)kalloc();
            if ((uint64_t)new_table == ADDRESS_INVALID) {
                restore_flags(sflags);
                return false;
            }

            // Only propagate USER and WRITE flags to intermediate entries. 
            // Restrictive flags like NX should only be set on the leaf PTE.
            current_table[index] = (uint64_t)new_table | PAGE_PRESENT | (flags & (PAGE_USER_MODE | PAGE_WRITE));
            asm volatile("" : : : "memory");  // Compiler barrier
        } else {
            current_table[index] |= (flags & (PAGE_USER_MODE | PAGE_WRITE));
        }

        uint64_t entry = current_table[index];
        
        // can't traverse through a large page
        if (entry & PAGE_HUGE) {
            restore_flags(sflags);
            return false;
        }
            
        current_table = (pte_t*)PHYS_TO_VIRT(entry & PAGE_ADDR_MASK);
    }

    uint64_t leaf_index = (page >> (12 + lowest_lvl * 9)) & 511;

    if (current_table[leaf_index] & PAGE_PRESENT) {
        restore_flags(sflags);
        return true; // Already mapped, consider it success
    }

    current_table[leaf_index] = frame | flags | PAGE_PRESENT;

    asm volatile("mfence" : : : "memory");
    flush_tlb();
    restore_flags(sflags);
    return true;
}

// Maps the kernel binary to the higher half using 4 KB pages with correct flags.
// The kernel sits at physical 0x200000 so two PD entries (2 × 2 MB) are needed.
void map_kernel() {
    uint64_t end = KERNEL_PHYS(__kernel_end);
    uint64_t current_phys = 0;

    for (int pd_idx = 0; current_phys < end && pd_idx < 2; pd_idx++) {
        pte_t *pt_phys, *pt_virt;

        if (pd_idx == 0) {
            pt_phys = (pte_t*)KERNEL_PHYS(pt_kernel);
            pt_virt = pt_kernel;
        } else {
            pt_phys = (pte_t*)bump_alloc();
            pt_virt = PHYS_TO_VIRT(pt_phys);
        }

        memset(pt_virt, 0, PAGE_SIZE);

        for (int pt_idx = 0; pt_idx < TABLE_ENTRIES && current_phys < end; pt_idx++, current_phys += PAGE_SIZE) {
            uint64_t flags = PAGE_PRESENT;
            if (current_phys < KERNEL_PHYS(__text_start))
                flags |= PAGE_WRITE | PAGE_EXECUTE_DISABLE;
            else if (current_phys < KERNEL_PHYS(__text_end))
                ; // text: read-only, executable
            else if (current_phys < KERNEL_PHYS(__rodata_end))
                flags |= PAGE_EXECUTE_DISABLE;
            else
                flags |= PAGE_WRITE | PAGE_EXECUTE_DISABLE;
            pt_virt[pt_idx] = current_phys | flags;
        }

        pd_kernel[pd_idx] = (uint64_t)pt_phys | PAGE_PRESENT | PAGE_WRITE;
    }

    memset(&pd_kernel[2], 0, sizeof(pte_t) * (TABLE_ENTRIES - 2));
    flush_tlb();
}

// Maps PHYS_GB gigabytes of physical RAM to PHYSICAL_OFFSET using 2 MB huge pages.
// Using 2 MB pages (not 1 GB) avoids the PDPE1GB CPUID requirement, making this
// work on hardware that may not support 1 GB huge pages.
void map_physical() {
    static bool bootinfo_translated = false;

    memset(pdpt_phys, 0, sizeof(pdpt_phys));
    for (int g = 0; g < PHYS_GB; g++) {
        for (int j = 0; j < TABLE_ENTRIES; j++) {
            pd_phys[g][j] = ((uint64_t)g * ONE_GIGABYTE + (uint64_t)j * TWO_MEGABYTE)
                            | PAGE_PRESENT | PAGE_WRITE | PAGE_EXECUTE_DISABLE | PAGE_HUGE;
        }
        pdpt_phys[g] = (uint64_t)KERNEL_PHYS(pd_phys[g])
                       | PAGE_PRESENT | PAGE_WRITE | PAGE_EXECUTE_DISABLE;
    }

    pml4_kernel[273] = KERNEL_PHYS(pdpt_phys) | PAGE_PRESENT | PAGE_EXECUTE_DISABLE | PAGE_WRITE;
    flush_tlb();

    if (!bootinfo_translated) {
        bootInfo = (BootInfo*)PHYS_TO_VIRT(bootInfo);
        bootInfo->mmap_addr = (uint64_t)PHYS_TO_VIRT(bootInfo->mmap_addr);
        bootinfo_translated = true;
    }
}

// Maps the GOP framebuffer into virtual memory at 0xFFFFFE8000000000.
// Handles framebuffers that are not 2MB-aligned by rounding the physical
// base down and adjusting the virtual address accordingly.
void map_gop() {
    uint64_t fb_phys   = bootInfo->framebuffer_base;
    gop_info.phys_fb   = fb_phys;
    uint64_t offset    = fb_phys & (TWO_MEGABYTE - 1);           // bytes into the first 2MB block
    uint64_t aligned   = fb_phys - offset;                       // 2MB-aligned physical base
    uint64_t size      = (uint64_t)bootInfo->pitch * bootInfo->height * 4; // framebuffer size in bytes
    GOP_NUM_PAGES = (offset + size + TWO_MEGABYTE - 1) / TWO_MEGABYTE;

    uint64_t* pdpt_gop = (uint64_t*)bump_alloc();
    uint64_t* pd_gop   = (uint64_t*)bump_alloc();

    if ((uint64_t)pdpt_gop == ADDRESS_INVALID || (uint64_t)pd_gop == ADDRESS_INVALID)
        return; // out of memory — framebuffer won't be mapped

    uint64_t* pdpt_gop_virt = PHYS_TO_VIRT(pdpt_gop);
    uint64_t* pd_gop_virt   = PHYS_TO_VIRT(pd_gop);

    memset(pdpt_gop_virt, 0, sizeof(pte_t) * TABLE_ENTRIES);
    memset(pd_gop_virt,   0, sizeof(pte_t) * TABLE_ENTRIES);

    for (uint64_t i = 0; i < GOP_NUM_PAGES; i++) {
        pd_gop_virt[i] = (aligned + i * TWO_MEGABYTE) | PAGE_PRESENT | PAGE_WRITE | PAGE_HUGE | PAGE_PAT_LARGE;
    }

    pdpt_gop_virt[0] = (uint64_t)pd_gop  | PAGE_PRESENT | PAGE_WRITE;
    pml4_kernel[509] = (uint64_t)pdpt_gop | PAGE_PRESENT | PAGE_WRITE;

    flush_tlb();

    // Virtual base + offset within the first 2MB page = exact framebuffer start
    bootInfo->framebuffer_base = GOP_VIRT_BASE + offset;
}

// Returns a physical address to a free frame. No mapping is provided and allocated pages can't be freed.
// Only use this function if the kernel mapping isn't complete yet.
void* bump_alloc() {
    static uint8_t* bump_entry = 0;
    static uint64_t bump_page = 0;

    if (bump_entry == 0)
        bump_entry = (uint8_t*)bootInfo->mmap_addr;

    uint8_t* end_of_map = (uint8_t*)bootInfo->mmap_addr + bootInfo->mmap_size;

    uint64_t kernel_start  = KERNEL_PHYS(__kernel_start);
    uint64_t kernel_end    = KERNEL_PHYS(__kernel_end);
    uint64_t mmap_start    = (uint64_t)VIRT_TO_PHYS(bootInfo->mmap_addr);
    uint64_t mmap_end      = mmap_start + bootInfo->mmap_size;
    uint64_t binfo_start   = (uint64_t)VIRT_TO_PHYS(bootInfo) & PAGE_ADDR_MASK;
    uint64_t binfo_end     = binfo_start + PAGE_SIZE;

    while (bump_entry < end_of_map) {
        efi_memory_descriptor_t* desc = (efi_memory_descriptor_t*)bump_entry;

        if (desc->type == EfiConventionalMemory || desc->type == EfiLoaderCode || desc->type == EfiLoaderData ||
            desc->type == EfiBootServicesCode   || desc->type == EfiBootServicesData) {
            if (bump_page >= desc->number_of_pages) {
                bump_entry += bootInfo->mmap_desc_size;
                bump_page = 0;
                continue;
            }

            uint64_t frame = desc->physical_start + (bump_page * PAGE_SIZE);

            if ((frame >= kernel_start && frame < kernel_end) ||
                (frame >= mmap_start   && frame < mmap_end)   ||
                (frame >= binfo_start  && frame < binfo_end)) {
                bump_page++;
                continue;
            }

            // Skip pages occupied by files preloaded by the bootloader
            bool skip = false;
            for (uint32_t fi = 0; fi < bootInfo->file_count; fi++) {
                uint64_t fstart = bootInfo->files[fi].data;
                uint64_t fend   = fstart + (((uint64_t)bootInfo->files[fi].size + PAGE_SIZE - 1) / PAGE_SIZE) * PAGE_SIZE;
                if (frame >= fstart && frame < fend) { skip = true; break; }
            }
            if (skip) { bump_page++; continue; }

            bump_page++;
            return (void*)frame;
        } else {
            bump_entry += bootInfo->mmap_desc_size;
            bump_page = 0;
        }
    }

    return (void*)ADDRESS_INVALID;
}


pte_t* get_kernel_pml4() {
    return (pte_t*)KERNEL_PHYS(pml4_kernel);
}

// Loads a new page table into the CR3 register and updates the current_page_table pointer
void load_page_table(pte_t* addr) {
    current_pml4 = addr;
    asm volatile("mov %0, %%cr3" : : "r"(addr) : "memory");
}

// Flushes the TLB by reloading the CR3 register
static inline void flush_tlb(void) {
    asm volatile(
        "mov %%cr3, %%rax\n\t"
        "mov %%rax, %%cr3"
        : 
        : 
        : "rax", "memory"
    );
}

// Removes the page table entry for a virtual address from a specific pml4
bool unmap_address_from_pml4(pte_t* pml4, void* virt) {
    uint64_t sflags = save_flags_and_cli();
    uint64_t page = PAGE_ROUNDDOWN((uint64_t)virt);
    pte_t* current_table = PHYS_TO_VIRT(pml4);

    for (int level = 3; level > 0; level--) {
        uint64_t index = (page >> (12 + level * 9)) & 511;

        if (!(current_table[index] & PAGE_PRESENT)) {
            restore_flags(sflags);
            return false;
        }

        uint64_t entry = current_table[index];
        if (entry & PAGE_HUGE) {
            current_table[index] = 0ULL;
            asm volatile("mfence" : : : "memory");
            // only flush if it's the current page table
            if (pml4 == current_pml4) flush_tlb();
            restore_flags(sflags);
            return true;
        }

        current_table = (pte_t*)PHYS_TO_VIRT(entry & PAGE_ADDR_MASK);
    }

    current_table[(page >> 12) & 511] = 0ULL;

    asm volatile("mfence" : : : "memory");
    if (pml4 == current_pml4) flush_tlb();
    restore_flags(sflags);
    return true;
}

// Removes the page table entry for a virtual address
bool unmap_address(void* virt) {
    return unmap_address_from_pml4(current_pml4, virt);
}

void unmap_user_gop(pte_t* pml4) {
    for (uint64_t i = 0; i < GOP_NUM_PAGES; i++) {
        unmap_address_from_pml4(pml4, (void*)(GOP_USERSPACE + i * TWO_MEGABYTE));
    }
}

// Creates a new pml4 and returns the physical address
pte_t* create_page_table() {
    pte_t* pml4_phys = (pte_t*)kalloc();
    pte_t* pml4_virt = PHYS_TO_VIRT(pml4_phys);

    // Zero the user space (first half of PML4)
    uint64_t sflags = save_flags_and_cli();
    memset(pml4_virt, 0, sizeof(pte_t) * 256);
    // Copy the kernel space (second half of PML4)
    memcpy(pml4_virt + 256, (pte_t*)pml4_kernel + 256, sizeof(pte_t) * 256);
    restore_flags(sflags);
    return pml4_phys;
}

// Generated by Gemini 3.1 on 2026-04-26
static void free_pt(pte_t pt_phys) {
    pte_t* pt_virt = PHYS_TO_VIRT(pt_phys);
    for (int i = 0; i < TABLE_ENTRIES; i++) {
        if (pt_virt[i] & PAGE_PRESENT) {
            kfree((void*)(pt_virt[i] & PAGE_ADDR_MASK));
        }
    }
    kfree((void*)pt_phys);
}

// Generated by Gemini 3.1 on 2026-04-26
static void free_pd(pte_t pd_phys) {
    pte_t* pd_virt = PHYS_TO_VIRT(pd_phys);
    for (int i = 0; i < TABLE_ENTRIES; i++) {
        if (pd_virt[i] & PAGE_PRESENT) {
            if (pd_virt[i] & PAGE_HUGE) {
                kfree((void*)(pd_virt[i] & PAGE_ADDR_MASK));
            } else {
                free_pt(pd_virt[i] & PAGE_ADDR_MASK);
            }
        }
    }
    kfree((void*)pd_phys);
}

// Generated by Gemini 3.1 on 2026-04-26
static void free_pdpt(pte_t pdpt_phys) {
    pte_t* pdpt_virt = PHYS_TO_VIRT(pdpt_phys);
    for (int i = 0; i < TABLE_ENTRIES; i++) {
        if (pdpt_virt[i] & PAGE_PRESENT) {
            if (pdpt_virt[i] & PAGE_HUGE) {
                kfree((void*)(pdpt_virt[i] & PAGE_ADDR_MASK));
            } else {
                free_pd(pdpt_virt[i] & PAGE_ADDR_MASK);
            }
        }
    }
    kfree((void*)pdpt_phys);
}

// Frees a page table including every user space table and page
void destroy_page_table(pte_t* pml4) {
    if (pml4 == current_pml4) {
        Manic("destroy_page_table: attempt to free current page table");
    }

    uint64_t sflags = save_flags_and_cli();
    pte_t* pml4_virt = PHYS_TO_VIRT(pml4);
    for (int i = 0; i < 256; i++) {
        if (pml4_virt[i] & PAGE_PRESENT) {
            free_pdpt(pml4_virt[i] & PAGE_ADDR_MASK);
        }
    }
    kfree((void*)pml4);
    restore_flags(sflags);
}
