// File intially generated by Claude Opus 4.6 on 2026-04-29
// was manually altered later
#include <stdint.h>

#define PI 3.14159265358979323846
#define DOUBLE_INT_BOUND 4503599627370496.0 // 2^52

// Note: These are baseline pure-software implementations using standard numerical 
// methods (Taylor series, Newton-Raphson, Halley's). They lack the extreme precision 
// tuning, hardware intrinsics (like x87 fsqrt), and exhaustive NaN/Infinity/subnormal 
// handling found in a production-grade libm (like glibc or musl).

double fabs(double x) { 
    return x < 0.0 ? -x : x; 
}

double sqrt(double x) {
    if (x < 0.0) return 0.0 / 0.0; // NaN
    if (x == 0.0 || x == 1.0) return x;
    
    double guess = x;
    for (int i = 0; i < 20; i++) {
        guess = 0.5 * (guess + x / guess);
    }
    return guess;
}

double floor(double x) {
    if (x >= DOUBLE_INT_BOUND || x <= -DOUBLE_INT_BOUND || x != x) return x;
    long long i = (long long)x;
    double d = (double)i;
    if (d == x || x >= 0.0) return d;
    return d - 1.0;
}

double ceil(double x) {
    if (x >= DOUBLE_INT_BOUND || x <= -DOUBLE_INT_BOUND || x != x) return x;
    long long i = (long long)x;
    double d = (double)i;
    if (d == x || x < 0.0) return d;
    return d + 1.0;
}

double round(double x) {
    return x < 0.0 ? ceil(x - 0.5) : floor(x + 0.5);
}

double fmod(double x, double y) {
    if (y == 0.0) return 0.0 / 0.0; // NaN
    double abs_x = fabs(x);
    double abs_y = fabs(y);
    double trunc_quotient = floor(abs_x / abs_y);
    double result = abs_x - trunc_quotient * abs_y;
    return x < 0.0 ? -result : result;
}

// Internal helper for trigonometric range reduction
static double reduce_angle(double x) {
    double reduced = fmod(x, 2.0 * PI);
    if (reduced < 0) reduced += 2.0 * PI;
    return reduced;
}

double sin(double x) {
    x = reduce_angle(x);
    if (x > PI) return -sin(x - PI);
    
    double term = x;
    double sum = x;
    for (int i = 1; i < 15; i++) {
        term *= -(x * x) / (2.0 * i * (2.0 * i + 1.0));
        sum += term;
    }
    return sum;
}

double cos(double x) {
    x = reduce_angle(x);
    if (x > PI) return -cos(x - PI);
    
    double term = 1.0;
    double sum = 1.0;
    for (int i = 1; i < 15; i++) {
        term *= -(x * x) / (2.0 * i * (2.0 * i - 1.0));
        sum += term;
    }
    return sum;
}

double tan(double x) {
    return sin(x) / cos(x);
}

double exp(double x) {
    double term = 1.0;
    double sum = 1.0;
    for (int i = 1; i < 50; i++) {
        term *= x / i;
        sum += term;
        if (fabs(term) < 1e-15) break;
    }
    return sum;
}

double log(double x) {
    if (x < 0.0) return 0.0 / 0.0; // NaN
    if (x == 0.0) return -1.0 / 0.0; // -Infinity
    
    // Halley's method
    double guess = 1.0; 
    for (int i = 0; i < 20; i++) {
        double e_guess = exp(guess);
        guess = guess + 2.0 * (x - e_guess) / (x + e_guess);
    }
    return guess;
}

double log2(double x) {
    return log(x) / 0.6931471805599453; // ln(2)
}

double log10(double x) {
    return log(x) / 2.302585092994046; // ln(10)
}

double pow(double base, double exp_val) {
    if (base == 0.0 && exp_val > 0.0) return 0.0;
    if (base == 0.0 && exp_val <= 0.0) return 1.0 / 0.0; // Infinity
    
    // Fast path for integer exponents
    if (floor(exp_val) == exp_val) {
        double result = 1.0;
        double b = base;
        long long e = (long long)fabs(exp_val);
        while (e > 0) {
            if (e % 2 == 1) result *= b;
            b *= b;
            e /= 2;
        }
        return exp_val < 0.0 ? 1.0 / result : result;
    }
    
    if (base < 0.0) return 0.0 / 0.0; // NaN for fractional power of negative
    return exp(exp_val * log(base));
}

double atan(double x) {
    int sign = (x < 0) ? -1 : 1;
    x = fabs(x);
    int inverted = 0;
    
    if (x > 1.0) {
        x = 1.0 / x;
        inverted = 1;
    }
    
    // Taylor series for |x| <= 1
    double term = x;
    double sum = x;
    for (int i = 1; i < 30; i++) {
        term *= -x * x;
        sum += term / (2.0 * i + 1.0);
    }
    
    if (inverted) sum = (PI / 2.0) - sum;
    return sign * sum;
}

double atan2(double y, double x) {
    if (x > 0.0) return atan(y / x);
    if (x < 0.0 && y >= 0.0) return atan(y / x) + PI;
    if (x < 0.0 && y < 0.0) return atan(y / x) - PI;
    if (x == 0.0 && y > 0.0) return PI / 2.0;
    if (x == 0.0 && y < 0.0) return -PI / 2.0;
    return 0.0; // Undefined at (0,0), standard typically returns 0.0
}